In [7]:
import torch

In [8]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([-62, -91, -78,  66, -63,  77])


In [10]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [12]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones = torch.ones(4,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [20]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [21]:
logspace = torch.logspace(3, 10, steps=5)
logspace

tensor([1.0000e+03, 5.6234e+04, 3.1623e+06, 1.7783e+08, 1.0000e+10])

In [23]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])