In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

In [ ]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

In [ ]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")
print(rand)

In [ ]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)
# будем использовать это для предсказания по вероятности

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

In [ ]:
# Операция конкатенации тензоров 
# Будем использовать для генерации
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

In [ ]:
out = torch.tril(torch.ones(5,5))
out

In [ ]:
out = torch.triu(torch.ones(5,5))
out

In [ ]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

In [ ]:
torch.exp(out)


In [ ]:
# transpose
input = torch.zeros(2,3,4)
out = input.transpose(0, 2)
out.shape

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimention
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

In [ ]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
# линейное преобразование 
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

In [ ]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

In [ ]:
# initialize on ebedding layer
vocab_size = 80
embeding_dim = 6
embeding = nn.Embedding(vocab_size, embeding_dim)
embeding

# create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# apply embedding layer
embedded_output = embeding(input_indices)

# the output shape will be a tensor of shape (4, 100), where 4 is the number of indices in the input tensor 
# and 100 is the dimensionality of the embedding layer.
print(embedded_output.shape)
print(embedded_output)

In [ ]:
a = torch.tensor([[1, 2],[3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print (a @ b)

In [ ]:
int_64 = torch.randint(2, (3, 2)).float()
print(int_64)
float_32 = torch.rand(2,3)
print(float_32)

result = torch.matmul(int_64, float_32)
print(result)

In [ ]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
print(a.shape)

In [ ]:
input = torch.rand((4,8,10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
print(output[:, -1, :])

In [53]:
# Relu
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.relu(x)
x,y

(tensor([-0.0500]), tensor([0.]))

In [54]:
# Sigmoid
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)
x,y

(tensor([-0.0500]), tensor([0.4875]))

In [56]:
# Tanh
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.tanh(x)
x,y

(tensor([-0.0500]), tensor([-0.0500]))