In [6]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [7]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000


In [8]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")
print(rand)

0.01138449
0.12362242
tensor([[[[1.7355e-02, 1.0483e-01, 1.6362e-03,  ..., 6.0660e-01,
           4.6303e-01, 7.1948e-01],
          [4.7026e-01, 9.4603e-02, 8.4347e-02,  ..., 1.0421e-01,
           1.9576e-02, 2.9285e-01],
          [3.6081e-01, 7.6656e-02, 1.7634e-01,  ..., 3.8804e-01,
           8.2695e-01, 1.0481e-01],
          ...,
          [1.7452e-01, 5.9490e-01, 5.6951e-02,  ..., 1.1840e-01,
           4.8881e-01, 8.6000e-01],
          [7.8167e-01, 1.7335e-01, 1.7056e-01,  ..., 2.6728e-01,
           1.6969e-01, 8.8381e-01],
          [7.9960e-01, 5.2507e-01, 1.9621e-01,  ..., 3.1308e-01,
           5.3459e-01, 6.5823e-01]],

         [[6.7561e-01, 4.4429e-01, 1.0647e-01,  ..., 7.2162e-03,
           1.8502e-01, 5.9159e-02],
          [1.3754e-01, 4.1756e-01, 7.7454e-01,  ..., 7.0019e-01,
           5.9732e-01, 2.1636e-01],
          [8.4332e-01, 4.4060e-01, 7.9227e-04,  ..., 5.0559e-01,
           5.1867e-01, 4.4572e-01],
          ...,
          [1.2334e-01, 2.6867e-01, 4.

In [9]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)
# будем использовать это для предсказания по вероятности

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [10]:
# Операция конкатенации тензоров 
# Будем использовать для генерации
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [11]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [12]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [13]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [14]:
torch.exp(out)


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [15]:
# transpose
input = torch.zeros(2,3,4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [16]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimention
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
# линейное преобразование 
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ -2.1393, -14.6320,  -8.6831], grad_fn=<SqueezeBackward4>)


In [18]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0321, 0.0871, 0.2369, 0.6439])


In [23]:
# initialize on ebedding layer
vocab_size = 80
embeding_dim = 6
embeding = nn.Embedding(vocab_size, embeding_dim)
embeding

# create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# apply embedding layer
embedded_output = embeding(input_indices)

# the output shape will be a tensor of shape (4, 100), where 4 is the number of indices in the input tensor 
# and 100 is the dimensionality of the embedding layer.
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.8400,  1.1697, -1.5314,  1.6491,  1.0780, -0.5045],
        [-1.3411,  0.2579,  0.7511, -0.3498,  1.8727,  0.7202],
        [ 0.2392,  0.1191,  0.5010, -1.6344, -0.0207, -0.3879],
        [-0.0185, -0.6629, -1.1495, -0.4991, -0.0279, -0.8198]],
       grad_fn=<EmbeddingBackward0>)


In [26]:
a = torch.tensor([[1, 2],[3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print (a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [44]:
int_64 = torch.randint(2, (3, 2)).float()
print(int_64)
float_32 = torch.rand(2,3)
print(float_32)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[1., 1.],
        [1., 0.],
        [0., 0.]])
tensor([[0.0721, 0.3841, 0.3177],
        [0.4261, 0.2379, 0.6112]])
tensor([[0.4982, 0.6219, 0.9289],
        [0.0721, 0.3841, 0.3177],
        [0.0000, 0.0000, 0.0000]])
